from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import FileResponse
from sqlalchemy.orm import Session
from typing import List
from datetime import datetime
import os
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak
from reportlab.lib.units import inch
from ..database import get_db
from ..models import User, GeneratedReport, ReportTemplate, Project, Task, Inventory
from ..schemas import ReportGenerateRequest, GeneratedReport as GeneratedReportSchema, ReportTemplate as ReportTemplateSchema
from ..auth import get_current_user

def _eligible_projects_for_user(db: Session, user: User):
    from ..models import Project, ProjectAssignment
    if user.role == 'admin':
        return db.query(Project.project_id, Project.project_name).all()
    elif user.role == 'project_manager':
        return db.query(Project.project_id, Project.project_name).filter(Project.created_by == user.user_id).all()
    else:
        assigned = db.query(ProjectAssignment.project_id).filter(ProjectAssignment.user_id == user.user_id)
        return db.query(Project.project_id, Project.project_name).filter(Project.project_id.in_(assigned)).all()

def _allowed_report_types_for_role(role: str):
    if role in ('admin', 'project_manager'):
        return ['project', 'task', 'inventory', 'financial']
    if role in ('engineer', 'technician'):
        return ['task', 'inventory']
    return []


router = APIRouter()

REPORTS_DIR = "uploads/reports"
os.makedirs(REPORTS_DIR, exist_ok=True)

@router.get("/available-projects", response_model=List[dict])
def get_available_projects_for_reports(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Get projects available for report generation based on user role:
    - Admin: all projects
    - Project Manager: only projects they created
    - Engineer/Technician: projects they're assigned to (but they can't generate reports)
    """
    if current_user.role == 'admin':
        # Admin can see all projects
        projects = db.query(Project).filter(Project.status != 'cancelled').all()
    elif current_user.role == 'project_manager':
        # Project managers see only projects they created
        projects = db.query(Project).filter(
            Project.created_by == current_user.user_id,
            Project.status != 'cancelled'
        ).all()
    else:
        # Engineers and technicians (though they can't generate, useful for viewing context)
        from ..models import ProjectAssignment
        assigned_project_ids = db.query(ProjectAssignment.project_id).filter(
            ProjectAssignment.user_id == current_user.user_id
        ).distinct().all()
        assigned_project_ids = [pid[0] for pid in assigned_project_ids]
        
        projects = db.query(Project).filter(
            Project.project_id.in_(assigned_project_ids),
            Project.status != 'cancelled'
        ).all()
    
    return [
        {
            "project_id": p.project_id,
            "project_name": p.project_name,
            "status": p.status
        }
        for p in projects
    ]

@router.get("/", response_model=List[GeneratedReportSchema])
def get_reports(
    skip: int = 0,
    limit: int = 100,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Get generated reports based on user role:
    - Admin: sees all reports
    - Project Manager: sees only reports from projects they created
    - Engineer/Technician: sees only reports related to their assigned projects
    """
    if current_user.role == 'admin':
        # Admin sees all reports
        reports = db.query(GeneratedReport).offset(skip).limit(limit).all()
    elif current_user.role == 'project_manager':
        # Project managers see only reports from projects they created
        created_project_ids = db.query(Project.project_id).filter(
            Project.created_by == current_user.user_id
        ).all()
        created_project_ids = [pid[0] for pid in created_project_ids]
        
        # Filter reports that have project_ids matching PM's projects
        all_reports = db.query(GeneratedReport).offset(skip).limit(limit).all()
        reports = []
        for report in all_reports:
            # Check if report was generated by this PM or is for their projects
            if report.generated_by == current_user.user_id:
                reports.append(report)
            elif report.parameters and 'project_ids' in report.parameters:
                report_project_ids = report.parameters.get('project_ids', [])
                if report_project_ids and any(pid in created_project_ids for pid in report_project_ids):
                    reports.append(report)
            elif report.parameters and 'project_id' in report.parameters:
                if report.parameters['project_id'] in created_project_ids:
                    reports.append(report)
    else:
        # Engineers and technicians see only reports for their assigned projects
        # and only task/inventory type reports (read-only access)
        from ..models import ProjectAssignment
        assigned_project_ids = db.query(ProjectAssignment.project_id).filter(
            ProjectAssignment.user_id == current_user.user_id
        ).distinct().all()
        assigned_project_ids = [pid[0] for pid in assigned_project_ids]
        
        # Filter reports based on allowed report types for role
        allowed_types = ['task', 'inventory']
        
        # Get all reports and filter them
        all_reports = db.query(GeneratedReport).filter(
            GeneratedReport.report_type.in_(allowed_types)
        ).offset(skip).limit(limit).all()
        
        reports = []
        for report in all_reports:
            # Check if report has project_ids in parameters
            if report.parameters and 'project_ids' in report.parameters:
                report_project_ids = report.parameters.get('project_ids', [])
                # Only include if at least one project ID matches user's assigned projects
                if report_project_ids and any(pid in assigned_project_ids for pid in report_project_ids):
                    reports.append(report)
            elif report.parameters and report.parameters.get('project_id'):
                # Handle single project_id case
                if report.parameters['project_id'] in assigned_project_ids:
                    reports.append(report)
            elif report.report_type == 'inventory':
                # Inventory reports without specific project can be viewed
                # but only if they were generated for projects the user is assigned to
                # Skip global inventory reports unless they relate to assigned projects
                if report.parameters and 'project_id' in report.parameters:
                    if report.parameters['project_id'] in assigned_project_ids:
                        reports.append(report)
                elif not report.parameters or not report.parameters.get('project_id'):
                    # For global inventory reports, only show if user has at least one assigned project
                    if assigned_project_ids:
                        reports.append(report)
    
    # Enrich reports with project_name
    enriched_reports = []
    for report in reports:
        report_dict = {
            "report_id": report.report_id,
            "report_name": report.report_name,
            "report_type": report.report_type,
            "file_path": report.file_path,
            "parameters": report.parameters,
            "generated_by": report.generated_by,
            "generated_at": report.generated_at,
            "project_name": None  # Default
        }
        
        # Extract project_name from parameters
        if report.parameters:
            project_id = report.parameters.get('project_id')
            if not project_id and report.parameters.get('project_ids'):
                # Use first project_id if multiple
                project_ids = report.parameters.get('project_ids', [])
                project_id = project_ids[0] if project_ids else None
            
            if project_id:
                project = db.query(Project).filter(Project.project_id == project_id).first()
                if project:
                    report_dict["project_name"] = project.project_name
        
        enriched_reports.append(report_dict)
    
    return enriched_reports

@router.get("/templates", response_model=List[ReportTemplateSchema])
def get_report_templates(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Get all report templates"""
    templates = db.query(ReportTemplate).all()
    
    # If no templates exist, create default ones
    if not templates:
        default_templates = [
            ReportTemplate(
                template_name="Project Summary",
                report_type="project",
                description="Summary of all projects",
                is_default=True,
                created_by=current_user.user_id
            ),
            ReportTemplate(
                template_name="Task Report",
                report_type="task",
                description="Detailed task report",
                is_default=True,
                created_by=current_user.user_id
            ),
            ReportTemplate(
                template_name="Inventory Report",
                report_type="inventory",
                description="Inventory levels and status",
                is_default=True,
                created_by=current_user.user_id
            ),
        ]
        for template in default_templates:
            db.add(template)
        db.commit()
        templates = db.query(ReportTemplate).all()
    
    return templates

@router.post("/generate", response_model=GeneratedReportSchema)
def generate_report(
    report_request: ReportGenerateRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Generate a new report with actual PDF file
    - Only Admin/PM can generate reports
    - Project Managers can only generate reports for projects they created
    - Engineer/Technician can only view reports
    """
    # Only admins and project managers can generate reports
    if current_user.role not in ['admin', 'project_manager']:
        raise HTTPException(
            status_code=403, 
            detail="Only admins and project managers can generate reports"
        )
    
    # Validate project ownership for project managers
    if current_user.role == 'project_manager' and report_request.project_id:
        project = db.query(Project).filter(
            Project.project_id == report_request.project_id,
            Project.created_by == current_user.user_id
        ).first()
        if not project:
            raise HTTPException(
                status_code=403,
                detail="You can only generate reports for projects you created"
            )
    
    # Create filename
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    filename = f"{report_request.report_name.replace(' ', '_')}_{timestamp}.pdf"
    file_path = os.path.join(REPORTS_DIR, filename)
    
    # Generate PDF
    doc = SimpleDocTemplate(file_path, pagesize=letter)
    story = []
    styles = getSampleStyleSheet()
    
    # Title
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#1a5490'),
        spaceAfter=30,
    )
    story.append(Paragraph(report_request.report_name, title_style))
    story.append(Spacer(1, 0.2*inch))
    
    # Report Info
    report_info = [
        ['Report Name:', report_request.report_name],
    ]
    
    # Add project name if project_id is provided
    if report_request.project_id:
        project = db.query(Project).filter(Project.project_id == report_request.project_id).first()
        if project:
            report_info.append(['Project Name:', project.project_name])
    
    report_info.extend([
        ['Type:', report_request.report_type.title()],
        ['Generated By:', current_user.full_name],
        ['Generated On:', datetime.now().strftime('%Y-%m-%d %H:%M:%S')],
    ])
    info_table = Table(report_info, colWidths=[2*inch, 4*inch])
    info_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#e8f5f1')),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('GRID', (0, 0), (-1, -1), 1, colors.grey),
    ]))
    story.append(info_table)
    story.append(Spacer(1, 0.3*inch))
    
    # Generate content based on report type
    if report_request.report_type == 'project':
        generate_project_report_content(story, report_request, db, styles, current_user)
    elif report_request.report_type == 'task':
        generate_task_report_content(story, report_request, db, styles, current_user)
    elif report_request.report_type == 'inventory':
        generate_inventory_report_content(story, report_request, db, styles)
    elif report_request.report_type == 'financial':
        generate_financial_report_content(story, report_request, db, styles, current_user)
    else:
        story.append(Paragraph(f"Report type '{report_request.report_type}' content generation in progress.", styles['Normal']))
    
    # Build PDF
    doc.build(story)
    
    # Store project_id in parameters for filtering
    params = report_request.dict()
    if report_request.project_id:
        params['project_ids'] = [report_request.project_id]
    
    # Create database record
    new_report = GeneratedReport(
        report_name=report_request.report_name,
        report_type=report_request.report_type,
        file_path=file_path,
        parameters=params,
        generated_by=current_user.user_id
    )
    
    db.add(new_report)
    db.commit()
    db.refresh(new_report)
    
    return new_report

def generate_project_report_content(story, report_request, db, styles, current_user):
    """Generate project report content"""
    story.append(Paragraph("Project Report", styles['Heading2']))
    story.append(Spacer(1, 0.2*inch))
    
    # Get projects
    query = db.query(Project)
    if report_request.project_ids:
        query = query.filter(Project.project_id.in_(report_request.project_ids))
    projects = query.all()
    
    if projects:
        # Project Overview Section
        story.append(Paragraph("Project Overview", styles['Heading3']))
        story.append(Spacer(1, 0.1*inch))
        data = [['Project Name', 'Status', 'Start Date', 'End Date', 'Budget']]
        for project in projects:
            data.append([
                project.project_name,
                project.status,
                str(project.start_date) if project.start_date else 'N/A',
                str(project.end_date) if project.end_date else 'N/A',
                f"${project.budget:,.2f}" if project.budget else 'N/A'
            ])
            
        # Create and style the project overview table
        project_table = Table(data, colWidths=[2*inch, 1.2*inch, 1.2*inch, 1.2*inch, 1.2*inch])
        project_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1a5490')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 11),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('LEFTPADDING', (0, 0), (-1, -1), 10),
            ('RIGHTPADDING', (0, 0), (-1, -1), 10),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ]))
        story.append(project_table)
        story.append(Spacer(1, 0.4*inch))
            
        # Add Tasks Section for each project
        for project in projects:
            story.append(Paragraph(f"Tasks for {project.project_name}", styles['Heading4']))
            story.append(Spacer(1, 0.1*inch))
            
            tasks = db.query(Task).filter(Task.project_id == project.project_id).all()
            if tasks:
                task_data = [['Task Name', 'Status', 'Priority', 'Due Date']]
                for task in tasks:
                    task_data.append([
                        task.task_name,
                        task.status,
                        task.priority,
                        str(task.due_date) if task.due_date else 'N/A'
                    ])
                task_table = Table(task_data, colWidths=[2.5*inch, 1*inch, 1*inch, 1.2*inch])
                task_table.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1a5490')),
                    ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                    ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('FONTSIZE', (0, 0), (-1, 0), 10),
                    ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
                    ('TOPPADDING', (0, 0), (-1, -1), 8),
                    ('LEFTPADDING', (0, 0), (-1, -1), 10),
                    ('RIGHTPADDING', (0, 0), (-1, -1), 10),
                    ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                    ('GRID', (0, 0), (-1, -1), 1, colors.black)
                ]))
                story.append(task_table)
                story.append(Spacer(1, 0.3*inch))
            else:
                story.append(Paragraph("No tasks found for this project.", styles['Normal']))
                story.append(Spacer(1, 0.3*inch))
    else:
        story.append(Paragraph("No projects found.", styles['Normal']))

def generate_task_report_content(story, report_request, db, styles, current_user):
    """Generate task report content"""
    story.append(Paragraph("Task Report", styles['Heading2']))
    story.append(Spacer(1, 0.2*inch))
    
    # Get tasks
    query = db.query(Task).join(Project)
    if report_request.project_ids:
        query = query.filter(Task.project_id.in_(report_request.project_ids))
    tasks = query.order_by(Task.status, Task.priority).all()
    
    if tasks:
        # Task Overview
        data = [['Task Name', 'Project', 'Status', 'Priority', 'Due Date', 'Assigned To']]
        for task in tasks:
            project = db.query(Project).filter(Project.project_id == task.project_id).first()
            assignee = db.query(User).filter(User.user_id == task.assigned_to).first() if task.assigned_to else None
            
            data.append([
                task.task_name[:30] + '...' if len(task.task_name) > 30 else task.task_name,
                project.project_name if project else 'N/A',
                task.status,
                task.priority,
                str(task.due_date) if task.due_date else 'N/A',
                assignee.full_name if assignee else 'Unassigned'
            ])
        
        task_table = Table(data, colWidths=[2.5*inch, 0.8*inch, 1*inch, 1*inch, 1.2*inch])
        task_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1a5490')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 11),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('LEFTPADDING', (0, 0), (-1, -1), 10),
            ('RIGHTPADDING', (0, 0), (-1, -1), 10),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ]))
        story.append(task_table)
        story.append(Spacer(1, 0.4*inch))
    else:
        story.append(Paragraph("No tasks found.", styles['Normal']))

def generate_inventory_report_content(story, report_request, db, styles):
    """Generate inventory report content with comprehensive sections"""
    story.append(Paragraph("Inventory Report", styles['Heading2']))
    story.append(Spacer(1, 0.2*inch))
    
    # Get all inventory items first
    query = db.query(Inventory)
    items = query.all()
    
    # Filter for low stock if requested
    if hasattr(report_request, 'custom_filters') and report_request.custom_filters and report_request.custom_filters.get('low_stock_only'):
        items = [item for item in items if item.quantity <= (item.reorder_level or 0)]
    
    if items:
        # Inventory Overview Section
        story.append(Paragraph("Current Inventory Status", styles['Heading3']))
        data = [['Item Name', 'Category', 'Quantity', 'Unit', 'Unit Price', 'Total Value', 'Status']]
        total_inventory_value = 0
        low_stock_items = []
        
        for item in items:
            total_value = item.quantity * (item.unit_price or 0)
            total_inventory_value += total_value
            status = 'Low Stock' if item.quantity <= (item.reorder_level or 0) else 'In Stock'
            
            if status == 'Low Stock':
                low_stock_items.append(item)
                
            data.append([
                item.item_name,
                item.category or 'N/A',
                str(item.quantity),
                item.unit or 'N/A',
                f"${item.unit_price:,.2f}" if item.unit_price else 'N/A',
                f"${total_value:,.2f}" if item.unit_price else 'N/A',
                status
            ])
        
        # Main inventory table with all columns
        story.append(Spacer(1, 0.1*inch))
        inventory_table = Table(data, colWidths=[1.5*inch, 1*inch, 0.8*inch, 0.8*inch, 1*inch, 1*inch, 1*inch])
        inventory_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1a5490')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('LEFTPADDING', (0, 0), (-1, -1), 10),
            ('RIGHTPADDING', (0, 0), (-1, -1), 10),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        story.append(inventory_table)
        
        # Add Summary Section
        story.append(Spacer(1, 0.4*inch))
        story.append(Paragraph("Inventory Summary", styles['Heading3']))
        summary_data = [
            ['Total Items:', str(len(items))],
            ['Total Inventory Value:', f"${total_inventory_value:,.2f}"],
            ['Low Stock Items:', str(len(low_stock_items))]
        ]
        story.append(Spacer(1, 0.1*inch))
        summary_table = Table(summary_data, colWidths=[2*inch, 4*inch])
        summary_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#e8f5f1')),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('LEFTPADDING', (0, 0), (-1, -1), 10),
            ('RIGHTPADDING', (0, 0), (-1, -1), 10),
            ('GRID', (0, 0), (-1, -1), 1, colors.grey)
        ]))
        story.append(summary_table)
        
        # Add Low Stock Items Section
        if low_stock_items:
            story.append(Spacer(1, 0.4*inch))
            story.append(Paragraph("Low Stock Items - Action Required", styles['Heading3']))
            low_stock_data = [['Item Name', 'Current Quantity', 'Reorder Level', 'Reorder Amount']]
            for item in low_stock_items:
                reorder_amount = max(0, (item.reorder_level or 0) - item.quantity)
                low_stock_data.append([
                    item.item_name,
                    str(item.quantity),
                    str(item.reorder_level or 'N/A'),
                    str(reorder_amount)
                ])
            
            story.append(Paragraph("Low Stock Items - Action Required", styles['Heading3']))
            story.append(Spacer(1, 0.1*inch))
            low_stock_table = Table(low_stock_data, colWidths=[2.5*inch, 1.5*inch, 1.5*inch, 1.5*inch])
            low_stock_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#ff4444')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
                ('TOPPADDING', (0, 0), (-1, -1), 8),
                ('LEFTPADDING', (0, 0), (-1, -1), 10),
                ('RIGHTPADDING', (0, 0), (-1, -1), 10),
                ('GRID', (0, 0), (-1, -1), 1, colors.black)
            ]))
            story.append(low_stock_table)
    else:
        story.append(Paragraph("No inventory items found.", styles['Normal']))

def generate_financial_report_content(story, report_request, db, styles, current_user):
    """Generate comprehensive financial report with project spending and inventory costs"""
    story.append(Paragraph("Financial Report", styles['Heading2']))
    story.append(Spacer(1, 0.2*inch))
    
    # PROJECT SPENDING SECTION
    story.append(Paragraph("Project Financial Overview", styles['Heading3']))
    story.append(Spacer(1, 0.1*inch))
    
    # Get projects
    query = db.query(Project)
    if report_request.project_ids:
        query = query.filter(Project.project_id.in_(report_request.project_ids))
    projects = query.all()
    
    if projects:
        # Project financial data
        data = [['Project Name', 'Budget', 'Spending', 'Remaining', 'Status']]
        total_budget = 0
        total_spending = 0
        
        for project in projects:
            budget = float(project.budget) if project.budget else 0
            spending = float(project.spending) if project.spending else 0
            remaining = budget - spending
            
            total_budget += budget
            total_spending += spending
            
            # Determine status color based on spending
            if spending > budget:
                status = 'Over Budget'
            elif spending >= budget * 0.9:
                status = 'Near Limit'
            else:
                status = 'On Track'
            
            data.append([
                project.project_name[:30] + '...' if len(project.project_name) > 30 else project.project_name,
                f"${budget:,.2f}",
                f"${spending:,.2f}",
                f"${remaining:,.2f}",
                status
            ])
        
        project_table = Table(data, colWidths=[2.5*inch, 1.3*inch, 1.3*inch, 1.3*inch, 1.3*inch])
        project_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1a5490')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('ALIGN', (1, 0), (-1, -1), 'RIGHT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('LEFTPADDING', (0, 0), (-1, -1), 10),
            ('RIGHTPADDING', (0, 0), (-1, -1), 10),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ]))
        story.append(project_table)
        
        # Project Summary
        story.append(Spacer(1, 0.4*inch))
        story.append(Paragraph("Project Financial Summary", styles['Heading4']))
        story.append(Spacer(1, 0.1*inch))
        summary_data = [
            ['Total Project Budget:', f"${total_budget:,.2f}"],
            ['Total Project Spending:', f"${total_spending:,.2f}"],
            ['Total Remaining Budget:', f"${(total_budget - total_spending):,.2f}"],
            ['Budget Utilization:', f"{(total_spending/total_budget*100 if total_budget > 0 else 0):.1f}%"]
        ]
        summary_table = Table(summary_data, colWidths=[2.5*inch, 3*inch])
        summary_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#e8f5f1')),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('ALIGN', (1, 0), (1, -1), 'RIGHT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 11),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('LEFTPADDING', (0, 0), (-1, -1), 10),
            ('RIGHTPADDING', (0, 0), (-1, -1), 10),
            ('GRID', (0, 0), (-1, -1), 1, colors.grey)
        ]))
        story.append(summary_table)
    else:
        story.append(Paragraph("No project financial data available.", styles['Normal']))
    
    # INVENTORY COSTS SECTION
    story.append(Spacer(1, 0.4*inch))
    story.append(Paragraph("Inventory Financial Overview", styles['Heading3']))
    story.append(Spacer(1, 0.1*inch))
    
    # Get inventory items
    items = db.query(Inventory).all()
    
    if items:
        # Inventory financial data
        inv_data = [['Item Name', 'Quantity', 'Unit Price', 'Total Value', 'Status']]
        total_inventory_value = 0
        low_stock_count = 0
        
        for item in items:
            unit_price = float(item.unit_price) if item.unit_price else 0
            quantity = item.quantity
            total_value = quantity * unit_price
            total_inventory_value += total_value
            
            status = 'Low Stock' if quantity <= (item.reorder_level or 0) else 'In Stock'
            if status == 'Low Stock':
                low_stock_count += 1
            
            inv_data.append([
                item.item_name[:30] + '...' if len(item.item_name) > 30 else item.item_name,
                str(quantity),
                f"${unit_price:,.2f}",
                f"${total_value:,.2f}",
                status
            ])
        
        inv_table = Table(inv_data, colWidths=[2.5*inch, 1.2*inch, 1.3*inch, 1.3*inch, 1.3*inch])
        inv_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1a5490')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('ALIGN', (1, 0), (-1, -1), 'RIGHT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('LEFTPADDING', (0, 0), (-1, -1), 10),
            ('RIGHTPADDING', (0, 0), (-1, -1), 10),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ]))
        story.append(inv_table)
        
        # Inventory Summary
        story.append(Spacer(1, 0.4*inch))
        story.append(Paragraph("Inventory Financial Summary", styles['Heading4']))
        story.append(Spacer(1, 0.1*inch))
        inv_summary_data = [
            ['Total Inventory Items:', str(len(items))],
            ['Total Inventory Value:', f"${total_inventory_value:,.2f}"],
            ['Low Stock Items:', f"{low_stock_count} items"]
        ]
        inv_summary_table = Table(inv_summary_data, colWidths=[2.5*inch, 3*inch])
        inv_summary_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#e8f5f1')),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('ALIGN', (1, 0), (1, -1), 'RIGHT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 11),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('LEFTPADDING', (0, 0), (-1, -1), 10),
            ('RIGHTPADDING', (0, 0), (-1, -1), 10),
            ('GRID', (0, 0), (-1, -1), 1, colors.grey)
        ]))
        story.append(inv_summary_table)
    else:
        story.append(Paragraph("No inventory financial data available.", styles['Normal']))
    
    # OVERALL FINANCIAL SUMMARY
    if projects or items:
        story.append(Spacer(1, 0.4*inch))
        story.append(Paragraph("Overall Financial Summary", styles['Heading3']))
        story.append(Spacer(1, 0.1*inch))
        
        overall_summary_data = [
            ['Total Project Budget:', f"${total_budget:,.2f}"],
            ['Total Project Spending:', f"${total_spending:,.2f}"],
            ['Total Inventory Value:', f"${total_inventory_value:,.2f}"],
            ['Combined Financial Position:', f"${(total_budget - total_spending + total_inventory_value):,.2f}"]
        ]
        overall_table = Table(overall_summary_data, colWidths=[3*inch, 3*inch])
        overall_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#1a5490')),
            ('TEXTCOLOR', (0, 0), (0, -1), colors.whitesmoke),
            ('BACKGROUND', (1, 0), (1, -1), colors.HexColor('#e8f5f1')),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('ALIGN', (1, 0), (1, -1), 'RIGHT'),
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 12),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 14),
            ('TOPPADDING', (0, 0), (-1, -1), 14),
            ('LEFTPADDING', (0, 0), (-1, -1), 12),
            ('RIGHTPADDING', (0, 0), (-1, -1), 12),
            ('GRID', (0, 0), (-1, -1), 2, colors.black),
        ]))
        story.append(overall_table)


@router.get("/{report_id}/download")
async def download_report(
    report_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Download a generated report"""
    report = db.query(GeneratedReport).filter(GeneratedReport.report_id == report_id).first()
    if not report:
        raise HTTPException(status_code=404, detail="Report not found")
    
    if not os.path.exists(report.file_path):
        raise HTTPException(status_code=404, detail="Report file not found on server")
    
    return FileResponse(
        path=report.file_path,
        filename=os.path.basename(report.file_path),
        media_type='application/pdf'
    )

@router.get("/{report_id}", response_model=GeneratedReportSchema)
def get_report(
    report_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Get a specific report"""
    report = db.query(GeneratedReport).filter(GeneratedReport.report_id == report_id).first()
    if not report:
        raise HTTPException(status_code=404, detail="Report not found")
    return report

@router.delete("/{report_id}")
def delete_report(
    report_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Delete a report"""
    if current_user.role not in ['admin', 'project_manager']:
        raise HTTPException(status_code=403, detail="Not authorized")
    
    report = db.query(GeneratedReport).filter(GeneratedReport.report_id == report_id).first()
    if not report:
        raise HTTPException(status_code=404, detail="Report not found")
    
    db.delete(report)
    db.commit()
    return {"message": "Report deleted successfully"}
